/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.majorityof1.www.geometry.hierarchy.shape3d;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


public class ThreeDGeomTest {
/*
  *  @Test public void testAppHasAGreeting() {
   *     App classUnderTest = new App();
    *    assertNotNull("app should have a greeting", classUnderTest.getGreeting());
	 */
		
		@Test
		void cubeSurfAreaTest() {
			Cube cb1 = new Cube(4.0);
			assertEquals(96.0, cb1.getSurfaceArea().doubleValue(), 0.01);
		}

		@Test
		void rectPrismSurfAreaTest() {
			RectPrism rp1 = new RectPrism(2.0, 1.0, 3.0);
			assertEquals(22.0, rp1.getSurfaceArea().doubleValue(), 0.01);
		}

		@Test
		void cubevolumeTest() {
			Cube cb1 = new Cube(3.0);
			assertEquals(27.0, cb1.getVolume().doubleValue(), 0.01);
		}

		@Test
		void rectPrismVolumeTest() {
			RectPrism rp1 = new RectPrism(2.0, 1.0, 3.0);
			assertEquals(6.0, rp1.getVolume().doubleValue(), 0.01);
		}
}
